model:
  n_embd: 2048
  n_layer: 24
  n_head: 16
  vocab_size: 50257
  block_size: 2048

training:
  batch_size: 524288
  micro_batch_size: 1
  seq_length: 1024
  nr_return_sequences: 5
  max_length: 30
  max_learning_rate: 0.0006
  min_learning_rate: 0.00006
  warmup_steps: 10
  max_steps: 50
  seed: 69
  weight_decay: 0.1
